-- 코드를 작성해주세요
WITH RECURSIVE RE AS(
    SELECT 1 CNT, ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CNT+1, A.ID, A.PARENT_ID
    FROM ECOLI_DATA A , RE B 
    WHERE A.PARENT_ID = B.ID AND CNT < 3
)

SELECT ID
FROM RE
WHERE CNT = 3
ORDER BY ID;