-- 코드를 입력하세요
SELECT if(DATE_FORMAT(START_DATE, "%m") = "08",8,if(DATE_FORMAT(START_DATE, "%m") = "09",9,10)) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%m") BETWEEN "08" AND "10"
    AND CAR_ID IN (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE_FORMAT(START_DATE, "%m") BETWEEN "08" AND "10"
        GROUP BY CAR_ID HAVING COUNT(*) >= 5)
GROUP BY MONTH, CAR_ID 
ORDER BY MONTH, CAR_ID DESC;