-- 코드를 작성해주세요
SELECT A.ID, IF(CHILD_COUNT IS NULL, 0, CHILD_COUNT) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN
(SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT FROM ECOLI_DATA GROUP BY PARENT_ID) B
ON A.ID = B.PARENT_ID
ORDER BY ID
