-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, GENDER, COUNT(DISTINCT S.USER_ID) USERS
FROM USER_INFO U, ONLINE_SALE S
WHERE U.USER_ID = S.USER_ID AND U.GENDER IS NOT NULL
GROUP BY MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER