-- 코드를 입력하세요
# SELECT CAR_ID, 
# IF(DATEDIFF(DATE("2022-10-16"),START_DATE)-1 <= 0, "대여 가능", IF(DATEDIFF(DATE("2022-10-16"),END_DATE)-1 <= 0, "대여 가능", "대여중")) AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID 
# ORDER BY CAR_ID DESC;

SELECT CAR_ID,
IF(MAX("2022-10-16" BETWEEN START_DATE AND END_DATE), "대여중", "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID 
ORDER BY CAR_ID DESC;