-- 코드를 작성해주세요
SELECT YEAR(B.DIFFERENTIATION_DATE) AS YEAR, (A.MAX_COLONY - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) A, ECOLI_DATA B
WHERE A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY 1, 2;



