-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, LENGTH
FROM FISH_INFO I INNER JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
ORDER BY 1